spring:
  profiles:
    active: ${PROFILES:prod}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:changelog/master.xml
logging:
  level:
    root: info
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
